config/routes.rb
Rentaroom::Application.routes.draw do
  devise_for :users

  resources :bookings

  resources :hotels

  root :to => 'hotels#index'

end

app/models/booking.rb
class Booking < ActiveRecord::Base
  attr_accessible :end_date, :hotel_id, :name, :start_date
  belongs_to :hotel
  
  after_create :checkin

  def checkin 
    self.hotel.guest_checkin
  end
  
  def checkout 
    self.hotel.guest_checkout
  end
end

app/models/hotel.rb
class Hotel < ActiveRecord::Base    
  attr_accessible :city, :name, :rooms_booked, :total_rooms, :price
  
  has_many :bookings
    
  def to_csv
    "#{self.city}, #{self.name},#{self.price}, #{self.rooms_available} "
  end
  
  def rooms_available
    self.total_rooms - self.rooms_booked
  end
  
  def guest_checkin
    self.rooms_booked += 1
    save
  end
  
  def guest_checkout
    self.rooms_booked -= 1
    save  
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :authenticate_user!
  
  def protect_with_key 
    redirect_to '/' unless params[:access_key] == "12345"
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  

  # GET /bookings
  # GET /bookings.json
  def index
    @bookings = Booking.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @bookings }
    end
  end

  # GET /bookings/1
  # GET /bookings/1.json
  def show
    @booking = Booking.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @booking }
    end
  end

  # GET /bookings/new
  # GET /bookings/new.json
  def new
    @booking = Booking.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @booking }
    end
  end

  # GET /bookings/1/edit
  def edit
    @booking = Booking.find(params[:id])
  end

  # POST /bookings
  # POST /bookings.json
  def create
    @booking = Booking.new(params[:booking])

    respond_to do |format|
      if @booking.save
        format.html { redirect_to @booking, notice: 'Booking was successfully created.' }
        format.json { render json: @booking, status: :created, location: @booking }
      else
        format.html { render action: "new" }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /bookings/1
  # PUT /bookings/1.json
  def update
    @booking = Booking.find(params[:id])

    respond_to do |format|
      if @booking.update_attributes(params[:booking])
        format.html { redirect_to @booking, notice: 'Booking was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bookings/1
  # DELETE /bookings/1.json
  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy

    respond_to do |format|
      format.html { redirect_to bookings_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/hotels_controller.rb
class HotelsController < ApplicationController
  # GET /hotels
  # GET /hotels.json
  def index
    @hotels = Hotel.all

    respond_to do |format|
      format.xml {render xml: @hotels}
      format.csv {send_data @hotels.map(&:to_csv)}
      format.html # index.html.erb
      format.json { render json: @hotels }
    end
  end

  # GET /hotels/1
  # GET /hotels/1.json
  def show
    @hotel = Hotel.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @hotel }
    end
  end

  # GET /hotels/new
  # GET /hotels/new.json
  def new
    @hotel = Hotel.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @hotel }
    end
  end

  # GET /hotels/1/edit
  def edit
    @hotel = Hotel.find(params[:id])
  end

  # POST /hotels
  # POST /hotels.json
  def create
    @hotel = Hotel.new(params[:hotel])

    respond_to do |format|
      if @hotel.save
        format.html { redirect_to @hotel, notice: 'Hotel was successfully created.' }
        format.json { render json: @hotel, status: :created, location: @hotel }
      else
        format.html { render action: "new" }
        format.json { render json: @hotel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /hotels/1
  # PUT /hotels/1.json
  def update
    @hotel = Hotel.find(params[:id])

    respond_to do |format|
      if @hotel.update_attributes(params[:hotel])
        format.html { redirect_to @hotel, notice: 'Hotel was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @hotel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hotels/1
  # DELETE /hotels/1.json
  def destroy
    @hotel = Hotel.find(params[:id])
    @hotel.destroy

    respond_to do |format|
      format.html { redirect_to hotels_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/hotels_helper.rb
module HotelsHelper
end

app/views/bookings/_form.html.erb
<%= form_for(@booking) do |f| %>
  <% if @booking.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@booking.errors.count, "error") %> prohibited this booking from being saved:</h2>

      <ul>
      <% @booking.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :hotel_id %><br />
    <%= f.select :hotel_id, Hotel.all.map { |hotel| [hotel.name, hotel.id] } %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :start_date %><br />
    <%= f.date_select :start_date %>
  </div>
  <div class="field">
    <%= f.label :end_date %><br />
    <%= f.date_select :end_date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bookings/edit.html.erb
<h1>Editing booking</h1>

<%= render 'form' %>

<%= link_to 'Show', @booking %> |
<%= link_to 'Back', bookings_path %>

app/views/bookings/index.html.erb
<h1>Listing bookings</h1>

<table>
  <tr>
    <th>Hotel</th>
    <th>Name</th>
    <th>Start date</th>
    <th>End date</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @bookings.each do |booking| %>
  <tr>
    <td><%= booking.hotel_id %></td>
    <td><%= booking.name %></td>
    <td><%= booking.start_date %></td>
    <td><%= booking.end_date %></td>
    <td><%= link_to 'Show', booking %></td>
    <td><%= link_to 'Edit', edit_booking_path(booking) %></td>
    <td><%= link_to 'Destroy', booking, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Booking', new_booking_path %>

app/views/bookings/new.html.erb
<h1>New booking</h1>

<%= render 'form' %>

<%= link_to 'Back', bookings_path %>

app/views/bookings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Hotel:</b>
  <%= @booking.hotel_id %>
</p>

<p>
  <b>Name:</b>
  <%= @booking.name %>
</p>

<p>
  <b>Start date:</b>
  <%= @booking.start_date %>
</p>

<p>
  <b>End date:</b>
  <%= @booking.end_date %>
</p>


<%= link_to 'Edit', edit_booking_path(@booking) %> |
<%= link_to 'Back', bookings_path %>

app/views/hotels/_form.html.erb
<%= form_for(@hotel) do |f| %>
  <% if @hotel.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@hotel.errors.count, "error") %> prohibited this hotel from being saved:</h2>

      <ul>
      <% @hotel.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :city %><br />
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :rooms_booked %><br />
    <%= f.text_field :rooms_booked %>
  </div>

  <div class="field">
    <%= f.label :total_rooms %><br />
    <%= f.text_field :total_rooms %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </div>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/hotels/edit.html.erb
<h1>Editing hotel</h1>

<%= render 'form' %>

<%= link_to 'Show', @hotel %> |
<%= link_to 'Back', hotels_path %>

app/views/hotels/index.html.erb
<h1>Listing hotels</h1>

<table>
  <tr>
    <th>Name</th>
    <th>City</th>
    <th>Rooms Available</th>
    <th>Price</th>
    <th></th>
  </tr>

<% @hotels.each do |hotel| %>
  <tr>
    <td><%= hotel.name %></td>
    <td><%= hotel.city %></td>
    <td align='center'><%= hotel.rooms_available %></td>    
    <td>$<%= hotel.price %></td>        
    <td><%= link_to 'Show', hotel %></td>
    <td><%= link_to 'Edit', edit_hotel_path(hotel) %></td>
    <td><%= link_to 'Destroy', hotel, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Hotel', new_hotel_path %>

app/views/hotels/new.html.erb
<h1>New hotel</h1>

<%= render 'form' %>

<%= link_to 'Back', hotels_path %>

app/views/hotels/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @hotel.name %>
</p>

<p>
  <b>City:</b>
  <%= @hotel.city %>
</p>

<p>
  <b>Rooms Available:</b>
  <%= @hotel.rooms_available %>
</p>

<p>
  <b>Price:</b>
  <%= @hotel.price %>
</p>



<%= link_to 'Edit', edit_hotel_path(@hotel) %> |
<%= link_to 'Back', hotels_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rentaroom</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>